build:
  image: xataz/docker-client:1.12.5
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/docker/.docker/config.json:/root/.docker/config.json
  environment:
    - UID=991
    - GID=991
  commands:
    - chmod +x build.sh
    - ./build.sh push
